name: 'Run a shell'
description: 'Run a shell'

runs:
  using: "composite"
  steps:
    - run: |
        echo "The"
        echo "Shell" 
      
    - name: zeShell
      run: ${{ github.action_path }}/myShell.sh
      shell: bash
