name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: boutinb/TestRepo/shellAction@master
