name: test-action

on:
  workflow_dispatch:
  #schedule:
  # UTC, https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  #- cron: '0/5 * * * *'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Run a one-line script
        run: echo Hello, world!!!!
        
      - uses: boutinb/TestRepo/myAction@master
