name: generate-translations

on:
  workflow_dispatch:
  #schedule:
  # UTC, https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  #- cron: '0/5 * * * *'

jobs:
  generate-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: "3.6.1"

      - uses: boutinb/TestRepo/translations@master

