name: generate-translations

on:
  workflow_dispatch:
  #schedule:
  # UTC, https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  #- cron: '0/5 * * * *'

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_KEY }}

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: "4.1.0"

      - uses: boutinb/jasp-actions/translations@master
